### ISSUE TITLE
make building of github pages automatic

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida-registry#10]
@giovannipizzi: this is what it looks like for now (quite minimal): https://aiidateam.github.io/aiida-registry/

**Comment by giovannipizzi** [comment]
Looks already good!
There are still some empty fields or containing "None", but I imagine this will be fixed.
I don't know if it's possible, but it would be nice to also know which entrypoints exist? Do you think it's feasible?
And also, if a person does a PR, and this gets merged, is the page regenerated? Or someone should trigger this action? (connected to this - the file used to generate the page is the one from which branch?)

**Comment by DropD** [comment]
I had initially added all the entry points, however it made the list very long and hard to read. The way to go with that is probably to have every plugin name link to a detail page.

At the moment a page build has to be triggered by running the generator script and then pushing to the gh-pages branch. Travis seems to have a simple way of doing that on every push to `master`.

Some of the empty fields will be fixed when I update the `aiida-vasp` registry entry some are missing fields in the setup.json of plugins, which we might want to provide a validator for, to use with `pre-commit` or travis.
