### ISSUE TITLE
introduce more relevant sort order?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#143]
This is a suggestion for Nicola to consider presenting the list of plugins in a more relevant order than alphabetic sorting.

E.g. something like most recent release / number of downloads / ...

**Comment by tkphd** [comment]
Related, it would be *awesome* if the top-level icons (Calculations, Data, Parsers, Workflows, Console Scripts, Other) were clickable buttons to filter the list to just those. Even adding a search box would be great.

**Comment by ltalirz** [comment]
Yeah... the registry should really be rewritten in a javascript framework like react.

I've dabbled a bit in it with http://atomistic.software/#/ - if anyone has a good suggestion for a template that might fit the AiiDA registry, let me know

**Comment by unkcpz** [comment]
Yearly commits counting introduced and closed by #245.

**Comment by ltalirz** [comment]
Thanks @AhmedBasem20 :-)
