### ISSUE TITLE
Plugin rendered page (on GitHub Pages) not updated anymore

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-registry#172]
It's three months that the [action 'webpage'](https://github.com/aiidateam/aiida-registry/blob/master/.github/workflows/webpage.yml) does not run anymore (as visible in the actions or in the last commit in the `gh-pages` branch).
This should have been triggered both nightly and on push to `master`.

@ltalirz any idea why? Did anything change on our side, or on GitHub's side?
Or some change in the syntax of the yml file (e.g. the [conditional that checks that we're on the main repo](https://github.com/aiidateam/aiida-registry/blob/94002d8c9c199f1c2aecb290c75c2baeca646236/.github/workflows/webpage.yml#L18))?

**Comment by ltalirz** [comment]
merged https://github.com/aiidateam/aiida-registry/pull/173 - let's see whether that fixes it

**Comment by ltalirz** [comment]
At least the `webpage` workflow is running on pushes to `master` again: https://github.com/aiidateam/aiida-registry/actions/runs/823599786

**Comment by giovannipizzi** [comment]
It seems the issue is that GitHub disables workflows if there is no repo activity for 60 days. This matches the pattern here (previous commit was on Dec 6th, actions stopped on Feb 4th):
https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

Let's see if they start being scheduled again, and if we have again limited activity, on the next merge we might need to re-enable the workflow manually
