### ISSUE TITLE
Add section for "Publications using this plugin"?

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-registry#176]
May be useful for people to get a more concrete idea of the kind of feature already available and working on the plugin.

**Comment by ltalirz** [comment]
Thanks for the suggestion @ramirezfranciscof 

I think the straightforward way to do this would be to simply mention this in the landing page of the plugin's documentation which is linked directly from the AiiDA registry.

I don't think we want to create an extra data item here in the registry so I'll be closing this - feel free to reopen if you think this needs further discussion.
