### ISSUE TITLE
Ordering for PRs

### ISSUE THREAD

**Issue by HaoZeke** [aiidateam/aiida-registry#178]
https://github.com/aiidateam/aiida-registry/issues/143 deals with the display ordering, but also it might be useful to consider adding instructions on where new plugins should be put in the `json` file itself. Since it is clearly not ordered by alphabet perhaps mentioning that it is OK to add to the bottom will be sufficient.

**Comment by ltalirz** [comment]
thanks, fixed in 89479f60cd9f3e910c67a02b83625ae1d3d7b5c8
