### ISSUE TITLE
deprecated `development_status`?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#191]
https://github.com/aiidateam/aiida-registry/pull/190 starts parsing the actual trove classifier for the development status of the plugin - and, as expected, [there are several cases](https://github.com/aiidateam/aiida-registry/pull/190#commitcomment-61476131) where it does not agree with the development status registered at the registry level.

In order to move towards standardization & reduce duplication of information, I propose the following changes:
 - the `development_status` key at the registry level is deprecated
 - for all plugins where there is already is a corresponding & matching development status trove classifier in the plugin source code, it is removed from the registry
 - for plugins where there is a discrepancy, or where there is no trove classifier, the plugin authors are notified
 - when registering a new plugin without pointing to a setup.json file (or similar), the development status will default to `planning`.

Sounds good @chrisjsewell ?

**Comment by chrisjsewell** [comment]
Yeh, the only use case i can think of, is if we want to mark a plugin as inactive, and the maintainer is not responding to our requests to change their classifier

**Comment by ltalirz** [comment]
I've removed the development status from packages with incongruent info and notified plugin developers.

For the moment we still keep the functionality around, both for those plugins that are still lacking trove classifiers in the repo & for the edgecases mentioned by Chris above.
