### ISSUE TITLE
Move from plugins.json to plugins.yaml

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#200]
There have been numerous cases of PRs adding new plugins failing because of JSON formatting issues (forgotten comma, forgotten braces, ...).

JSON isn't really meant to be edited by humans, so I propose to move from a `plugins.json` to a `plugins.yaml` file.
The programatically produced `plugins_metadata.json` can of course still remain in json format.

Before I make any changes in this direction: @yakutovicha are you currently using the `plugins.json` directly in the AiiDA lab or only the `plugins_metadata.json`?
I.e. can I move forward with this without breaking anything on your side?

**Comment by yakutovicha** [comment]
> Before I make any changes in this direction: @yakutovicha are you currently using the `plugins.json` directly in the AiiDA lab or only the `plugins_metadata.json`?
> I.e. can I move forward with this without breaking anything on your side?

Thanks for the heads up, @ltalirz. As far as I am aware we are not (directly) interacting with this repository from the AiiDAlab side. So from my side, there is no problem that you go ahead.
