### ISSUE TITLE
Open issue on plugin repos not distributing wheels

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-registry#202]
As discussed in https://github.com/aiidateam/aiida-registry/pull/201, it is best practice for package releases to upload both a source distribution and wheel (https://www.python.org/dev/peps/pep-0491/) to pypi.

Packages using setuptools should now be using `python -m build`
(See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)

**Comment by unkcpz** [comment]
Can this one be closed? We now get order the latest release by information from pypi. I close it, feel free to reopen it.
