### ISSUE TITLE
incorrect entry point classes shown on plugin registry

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#205]
![image](https://user-images.githubusercontent.com/1053245/151341370-21ce3018-eb4c-4c5d-a750-9c91ff34492b.png)

To investigate

**Comment by ltalirz** [comment]
@chrisjsewell is this a bug in the flit parser?

**Comment by chrisjsewell** [comment]
Oops this would be the reason: https://github.com/aiidateam/aiida-registry/blob/64c1766aae62fb835057f5386d4733435dc84186/plugins.yaml#L109

should we put aiida-diff on pypi anyway, so then it can pull from there

**Comment by ltalirz** [comment]
I'd be fine with putting it on PyPI

**Comment by ltalirz** [comment]
On second thought: fetching the data from PyPI this might make updating the plugin cutter (& aiida-diff) a bit more arduous.

Let me just fix the link for the time being.
