### ISSUE TITLE
Better indicate plugin development and maintenance state through labels

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-registry#220]
We could use labels such as PyPI download statistics and moderated categories such as `common-workflows` to better indicate the development and maintenance state of a plugin in the registry.

Related to #143 .

**Comment by ltalirz** [comment]
Happy to accept a PR for integrating PyPI download statistics.

As for other discoverability, there is https://github.com/aiidateam/aiida-registry/issues/215 which I haven't had time to come back to.
It works locally, just not on github actions, and it would give us access to detailed information of the workflows every plugin provides.

I think a page with more details on the available workflows will be a great way for newcomers to discover & browse through available capability.

**Comment by ltalirz** [comment]
The sorting by commits in the past year #245 is a good step into this direction (as is the sorting by most recent release). Closing this for the moment; feel free to reopen with new ideas
