### ISSUE TITLE
GSoC: UI polishing

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-registry#246]
UI polishing need to happened before the final release of the new registry page. @AhmedBasem20 
We keep this list and focus on things in a dedicate PR. Please keep this list update with more new requirement on UI.

- [x] The checkbox format and type.
- [x] #252
- [x] Each plugin name in the description page is better to be a bit larger.
- [x] Make the website responsive, fix the design on small screens.

**Comment by AhmedBasem20** [comment]
Hi @unkcpz, I'm about to finish this one, just have a question, should I add all plugins in the outlines section? or those with the extracted information only (calculations and workflows)?

**Comment by AhmedBasem20** [comment]
Or what do you think of making the outlines as a sidebar for all page content? Like "On this page" section on [AiiDA documentation page](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html).

**Comment by unkcpz** [comment]
> I'm about to finish this one, just have a question, should I add all plugins in the outlines section?

I think it makes more sense to outlines all plugins.

> Like "On this page" section on [AiiDA documentation page](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html).

If that is possible, it is super great! I am keen to learn how it is implemented. 😄

**Comment by AhmedBasem20** [comment]
Hi @unkcpz, I give the sidebar section a try but it seems a bit challenging. I'm not done with it yet but I wanted to keep you updated on the progress so I'll open a draft PR soon.
