### ISSUE TITLE
automatic testing of aiida plugins for dependency conflicts

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#67]
as mentioned in https://github.com/aiidalab/aiidalab-metapkg/issues/7, it would be helpful to 
  * create a Pipfile containing all aiida plugins with status >=development (or perhaps only >=production)
  * run `pipenv lock` on it to check for dependency conflicts

**Comment by ltalirz** [comment]
with the automatic installation testing based on the pip-url in place, this would be quite straightforward to add.

However, even aiida-core itself fails locking currently because of circus https://github.com/aiidateam/aiida-core/issues/2794

**Comment by unkcpz** [comment]
Will be addressed by #245

**Comment by ltalirz** [comment]
Done, thanks @AhmedBasem20 for his contribution :-)
